import React, { createContext, useContext, useState, useEffect } from "react";

type Language = "en" | "ar";

interface LanguageContextType {
    language: Language;
    setLanguage: (lang: Language) => void;
    t: (key: string) => string;
}

const translations = {
    en: {
        dashboard: "Dashboard",
        attendance: "Staff Attendance",
        hr: "HR Management",
        payroll: "Payroll",
        canteen: "Canteen",
        inventory: "Inventory",
        suppliers: "Suppliers",
        workshops: "Workshops",
        assets: "Assets Custody",
        reports: "Reports",
        profile: "My Profile",
        settings: "Settings",
        signout: "Sign Out",
        search: "Search...",
        notifications: "Notifications",
        viewAll: "View All",
        welcome: "Welcome back, Administrator",
        language: "العربية",
        totalEmployees: "Total Employees",
        todayAttendance: "Today Attendance",
        inventoryAlerts: "Inventory Alerts",
        monthlyExpenses: "Monthly Expenses",
        activeStaff: "Active Staff",
        onLeave: "On Leave",
        lateArrivals: "Late Arrivals",
        absent: "Absent",
        recentActivity: "Recent Activity",
        description: "Manage and monitor your school operations effectively.",
        totalAssets: "Total Assets",
        assigned: "Assigned",
        available: "Available",
        overdueReturns: "Overdue Returns",
        financialSummary: "Financial Summary",
        salaryDisbursed: "Salary Disbursed",
        totalDeductions: "Total Deductions",
        pendingPayments: "Pending Payments",
        dailySales: "Daily Sales",
        activeOrders: "Active Orders",
        outOfStock: "Out of Stock",
        hrDescription: "Manage employee records, contracts, and organizational structure.",
        attendanceDescription: "Track daily employee attendance and working hours.",
        payrollDescription: "Manage salaries, allowances, deductions, and payment processing.",
        canteenDescription: "Manage canteen menu, orders, and daily meal operations.",
        inventoryDescription: "Track and manage school inventory, stock levels, and supplies.",
        suppliersDescription: "Manage supplier relationships, contracts, and purchase orders.",
        workshopsDescription: "Schedule and manage professional development workshops and training sessions.",
        assetsDescription: "Track asset assignments, custody records, and equipment handovers.",
        reportsDescription: "Generate and view comprehensive operational reports and analytics.",
        profileDescription: "View and manage your personal information.",
        settingsDescription: "Configure system preferences and account settings.",
        employee: "Employee",
        position: "Position",
        department: "Department",
        joinDate: "Join Date",
        status: "Status",
        checkIn: "Check In",
        checkOut: "Check Out",
        Present: "Present",
        Absent: "Absent",
        Late: "Late",
        Paid: "Paid",
        Pending: "Pending",
        Active: "Active",
        Inactive: "Inactive",
        "On Leave": "On Leave",
        "Low Stock": "Low Stock",
        "In Stock": "In Stock",
        "Out of Stock": "Out of Stock",
        Completed: "Completed",
        Overdue: "Overdue",
        baseSalary: "Base Salary",
        allowances: "Allowances",
        deductions: "Deductions",
        netPay: "Net Pay",
        menuItem: "Menu Item",
        category: "Category",
        price: "Price",
        soldToday: "Sold Today",
        supplier: "Supplier",
        contact: "Contact",
        lastOrder: "Last Order",
        itemName: "Item Name",
        quantity: "Quantity",
        unit: "Unit",
        workshop: "Workshop",
        instructor: "Instructor",
        date: "Date",
        participants: "Participants",
        asset: "Asset",
        assignedTo: "Assigned To",
        personalInfo: "Personal Information",
        fullName: "Full Name",
        email: "Email",
        phone: "Phone",
        location: "Location",
        general: "General",
        security: "Security",
        systemName: "System Name",
        timezone: "Timezone",
        emailNotif: "Email Notifications",
        pushNotif: "Push Notifications",
        twoFactor: "Two-Factor Authentication",
        user: "User",
        action: "Action",
        time: "Time",
        Action: "Action",
        User: "User",
        Department: "Department",
        Time: "Time",
        Status: "Status",
        "Senior Teacher": "Senior Teacher",
        "Lab Technician": "Lab Technician",
        Teacher: "Teacher",
        Coordinator: "Coordinator",
        Coach: "Coach",
        "IT Support": "IT Support",
        "Main Course": "Main Course",
        Appetizer: "Appetizer",
        Beverage: "Beverage",
        Dessert: "Dessert",
        totalWorkshops: "Total Workshops",
        upcoming: "Upcoming",
        systemOverview: "System Overview",
        signoutConfirm: "Are you sure you want to sign out?",
        cancel: "Cancel",
        noData: "No data available",
        noDataDesc: "Data will appear here once the system is connected to the server",
        quickActions: "Quick Actions",
        systemStatus: "System Status",
        servers: "Servers",
        database: "Database",
        backup: "Backup",
        connected: "Connected",
        awaitingSetup: "Awaiting Setup",
        notConfigured: "Not Configured",
        noNotifications: "No notifications yet",
        weeklyAttendance: "Weekly Attendance Analytics",
        attendanceComparison: "Attendance rate comparison across week days",
        attendanceLabel: "Attendance",
        operational: "Operational",
        maintenance: "Maintenance",
        setupRequired: "Setup Required",
        welcomeTitle: "Welcome back",
        welcomeSubtitle: "Here's an overview of today's school operations",
        inactive: "Inactive",
        students: "Student Management",
        studentsDescription: "Manage student records, enrollment, and academic progress.",
        totalStudents: "Total Students",
        newEnrollments: "New Enrollments",
        activeStudents: "Active Students",
        graduated: "Graduated",
        rollNumber: "Roll No.",
        grade: "Grade",
        parentName: "Parent Name",
        studentClass: "Class",
        recentReports: "Recent Reports",
        filterReports: "Filter Reports",
        scheduleAutoReports: "Schedule Automated Reports",
        scheduleDesc: "Set up periodic reports to be delivered directly to your email every week.",
        startScheduling: "Start Scheduling Now",
        saveChanges: "Save Changes",
        changePassword: "Change Password",
        receiveEmailUpdates: "Receive system updates via email",
        browserPushNotif: "Browser push notifications",
        extraSecuritySMS: "Extra security layer via SMS",
        mealsServed: "Meals Served",
        menuItems: "Menu Items",
        totalItems: "Total Items",
        totalPaid: "Total Paid",
        sessionSecure: "Your current session will be closed and your account secured.",
        fullAccess: "Full Access",
        editDetails: "Edit Details",
        securityExcellent: "Security Status: Excellent",
        verifiedEmailPhone: "Email and phone verified successfully",
        adminDept: "General Administration",
        cairoEgypt: "Cairo, Egypt",
        adminTitle: "System Administrator",
        pendingFees: "Pending Fees",
        searchStudent: "Search Students...",
        searchInventory: "Search Inventory...",
        searchMenu: "Search Menu...",
        searchPayroll: "Search Payroll...",
        searchSuppliers: "Search Suppliers...",
        searchWorkshops: "Search Workshops...",
        searchAssets: "Search Assets...",
        allGrades: "All Grades",
        allClasses: "All Classes",
        allCategories: "All Categories",
        exportData: "Export Data",
        addStudent: "Add Student",
        addItem: "Add Item",
        addMeal: "Add Meal",
        processPayroll: "Process Payroll",
        addSupplier: "Add Supplier",
        addWorkshop: "Add Workshop",
        assignAsset: "Assign Asset",
        inStock: "In Stock",
        lowStock: "Low Stock",
        totalSuppliers: "Total Suppliers",
        pendingOrders: "Pending Orders",
        overdue: "Overdue",
        curriculum: "Curriculum Management",
        curriculumDescription: "Manage curriculum, courses, and teaching schedules.",
        grades: "Grades & Assessment",
        gradesDescription: "Track student grades, assessments, and academic performance.",
        library: "Library Management",
        libraryDescription: "Manage library books, borrowing, and digital resources.",
        transportation: "Transportation",
        transportationDescription: "Manage school buses, routes, and transportation.",
        parent_portal: "Parent Portal",
        parentPortalDescription: "Allow parents to track student progress and communicate.",
        notificationsSystem: "Notifications System",
        notificationsSystemDescription: "Send SMS, email, and push notifications.",
        advanced_reports: "Advanced Reports",
        advancedReportsDescription: "Generate detailed reports with analytics and visualizations.",
        events: "Events & Activities",
        eventsDescription: "Schedule and manage school events, competitions, and activities.",
        complaints: "Complaints & Suggestions",
        complaintsDescription: "Manage student and parent complaints and suggestions.",
        fees: "Fee Management",
        feesDescription: "Track student fees, invoices, and payment records.",
        archive: "Digital Archive",
        archiveDescription: "Store and manage digital documents and student records.",
        analytics: "Analytics Dashboard",
        analyticsDescription: "View advanced analytics, KPIs, and performance metrics.",
        courses: "Courses",
        activities: "Activities",
        September: "September",
        send: "Send",
        manageLand: "Manage Curriculum",
        gradeTable: "Grade Table",
        academicPerformance: "Academic Performance",
        borrowing: "Borrowing",
        searching: "Searching",
        busStatus: "Bus Status",
        parentConnect: "Parent Contact",
        teacherContact: "Teacher Contact",
        schoolAdmin: "School Admin",
        sendMessage: "Send Message",
        scheduleReport: "Schedule Report",
        competitionsHeld: "Competitions Held",
        complaintStatus: "Complaint Status",
        fileList: "File List",
        dashboardMetrics: "Dashboard Metrics",
        performanceMetrics: "Performance Metrics",
        attendanceRate: "Attendance Rate",
        parentSatisfaction: "Parent Satisfaction",
        overallGrowth: "Overall Growth",
        academicTrend: "Academic Trend",
        studentDistribution: "Student Distribution",
        morning: "Morning",
        noon: "Noon",
        afternoon: "Afternoon",
        evening: "Evening",
        used: "Used",
        documents: "Documents",
        certificates: "Certificates",
        urgent: "Urgent",
        views: "Views",
        message: "Message",
        primary: "Primary",
        preparatory: "Preparatory",
        secondary: "Secondary",
        averageRating: "Average Rating",
        Student: "Student",
        course: "Course",
        totalReports: "Total Reports",
        thisMonth: "This Month",
        scheduled: "Scheduled",
        pendingReview: "Pending Review",
        generated: "Generated",
        attendanceReport: "Monthly Attendance Report",
        attendanceReportDesc: "Detailed staff attendance statistics and trends",
        payrollSummary: "Payroll Summary",
        payrollSummaryDesc: "Complete breakdown of salaries, deductions, and allowances",
        inventoryReport: "Inventory Status Report",
        inventoryReportDesc: "Current stock levels and reorder alerts",
        financialReport: "Financial Overview",
        financialReportDesc: "Income, expenses, and budget utilization report",
        hrAnalytics: "HR Analytics",
        hrAnalyticsDesc: "Employee turnover, satisfaction, and department metrics",
        supplierReport: "Supplier Performance",
        supplierReportDesc: "Delivery timelines, quality ratings, and costs",
    },
    ar: {
        dashboard: "لوحة التحكم",
        attendance: "حضور الموظفين",
        hr: "إدارة الموارد البشرية",
        payroll: "الرواتب",
        canteen: "المقصف",
        inventory: "المخزون",
        suppliers: "الموردين",
        workshops: "الورش التدريبية",
        assets: "عهدة الأصول",
        reports: "التقارير",
        profile: "ملفي الشخصي",
        settings: "الإعدادات",
        signout: "تسجيل الخروج",
        search: "بحث...",
        notifications: "الإشعارات",
        viewAll: "عرض الكل",
        welcome: "مرحباً بك مجدداً، مدير النظام",
        language: "English",
        totalEmployees: "إجمالي الموظفين",
        todayAttendance: "حضور اليوم",
        inventoryAlerts: "تنبيهات المخزون",
        monthlyExpenses: "المصروفات الشهرية",
        activeStaff: "الموظفون النشطون",
        onLeave: "في إجازة",
        lateArrivals: "متأخرون",
        absent: "غائبون",
        recentActivity: "آخر النشاطات",
        description: "إدارة ومراقبة عمليات مدرستك بفعالية.",
        totalAssets: "إجمالي الأصول",
        assigned: "مُسندة",
        available: "متاحة",
        overdueReturns: "تأخر في الإرجاع",
        financialSummary: "الملخص المالي",
        salaryDisbursed: "الرواتب المصروفة",
        totalDeductions: "إجمالي الاستقطاعات",
        pendingPayments: "مدفوعات معلقة",
        dailySales: "المبيعات اليومية",
        activeOrders: "الطلبات النشطة",
        outOfStock: "نفذ من المخزون",
        hrDescription: "إدارة سجلات الموظفين والعقود والهيكل التنظيمي.",
        attendanceDescription: "تتبع حضور الموظفين اليومي وساعات العمل.",
        payrollDescription: "إدارة الرواتب والبدلات والاستقطاعات ومعالجة الدفع.",
        canteenDescription: "إدارة قائمة المقصف والطلبات وعمليات الوجبات اليومية.",
        inventoryDescription: "تتبع وإدارة مخزون المدرسة ومستويات المخزون والإمدادات.",
        suppliersDescription: "إدارة علاقات الموردين والعقود وأوامر الشراء.",
        workshopsDescription: "جدولة وإدارة ورش التطوير المهني والدورات التدريبية.",
        assetsDescription: "تتبع تعيينات الأصول وسجلات العهدة وتسليم المعدات.",
        reportsDescription: "إنشاء وعرض تقارير عمليات شاملة وتحليلات.",
        profileDescription: "عرض وإدارة معلوماتك الشخصية.",
        settingsDescription: "تكوين تفضيلات النظام وإعدادات الحساب.",
        employee: "الموظف",
        position: "المنصب",
        department: "القسم",
        joinDate: "تاريخ الانضمام",
        status: "الحالة",
        checkIn: "توقيت الحضور",
        checkOut: "توقيت الانصراف",
        Present: "حاضر",
        Absent: "غائب",
        Late: "متأخر",
        Paid: "مدفوع",
        Pending: "معلق",
        Active: "نشط",
        Inactive: "غير نشط",
        "On Leave": "في إجازة",
        "Low Stock": "مخزون منخفض",
        "In Stock": "متوفر",
        "Out of Stock": "نفذ من المخزون",
        Completed: "مكتمل",
        Overdue: "متأخر",
        baseSalary: "الراتب الأساسي",
        allowances: "البدلات",
        deductions: "الاستقطاعات",
        netPay: "صافي الراتب",
        menuItem: "الصنف",
        category: "الفئة",
        price: "السعر",
        soldToday: "المباع اليوم",
        supplier: "المورد",
        contact: "التواصل",
        lastOrder: "آخر طلب",
        itemName: "اسم الصنف",
        quantity: "الكمية",
        unit: "الوحدة",
        workshop: "الورشة",
        instructor: "المحاضر",
        date: "التاريخ",
        participants: "المشاركون",
        asset: "الأصل",
        assignedTo: "مُسند إلى",
        personalInfo: "المعلومات الشخصية",
        fullName: "الاسم الكامل",
        email: "البريد الإلكتروني",
        phone: "الهاتف",
        location: "الموقع",
        general: "عام",
        security: "الأمان",
        systemName: "اسم النظام",
        timezone: "المنطقة الزمنية",
        emailNotif: "إشعارات البريد",
        pushNotif: "إشعارات المتصفح",
        twoFactor: "المصادقة الثنائية",
        "Senior Teacher": "معلم أول",
        "Lab Technician": "فني مختبر",
        Teacher: "معلم",
        Coordinator: "منسق",
        Coach: "مدرب",
        "IT Support": "دعم فني",
        "Main Course": "طبق رئيسي",
        Appetizer: "مقبلات",
        Beverage: "مشروبات",
        Dessert: "حلويات",
        time: "الوقت",
        action: "الإجراء",
        user: "المستخدم",
        Action: "الإجراء",
        User: "المستخدم",
        Department: "القسم",
        Time: "الوقت",
        Status: "الحالة",
        System: "النظام",
        totalReports: "إجمالي التقارير",
        thisMonth: "هذا الشهر",
        scheduled: "مجدولة",
        pendingReview: "قيد المراجعة",
        generated: "تم الإنشاء",
        attendanceReport: "تقرير الحضور الشهري",
        attendanceReportDesc: "إحصائيات حضور الموظفين وتوجهاتهم بالتفصيل",
        payrollSummary: "ملخص الرواتب",
        payrollSummaryDesc: "تفصيل كامل للرواتب مع الاستقطاعات والبدلات",
        inventoryReport: "تقرير حالة المخزون",
        inventoryReportDesc: "مستويات المخزون الحالية وتنبيهات إعادة الطلب",
        financialReport: "نظرة عامة مالية",
        financialReportDesc: "تقرير الدخل والمصروفات واستخدام الميزانية",
        hrAnalytics: "تحليلات الموارد البشرية",
        hrAnalyticsDesc: "معدل دوران الموظفين ورضاهم ومقاييس الأقسام",
        supplierReport: "أداء الموردين",
        supplierReportDesc: "الجداول الزمنية للتسليم وتقييمات الجودة وتكاليفها",
        newEmployeeRegistered: "تسجيل موظف جديد",
        inventoryRestocked: "إعادة تعبئة المخزون",
        leaveRequestSubmitted: "تقديم طلب إجازة",
        payrollProcessed: "تم معالجة الرواتب",
        maintenanceRequest: "طلب صيانة",
        supplierInvoiceReceived: "استلام فاتورة مورد",
        mathematics: "الرياضيات",
        operations: "العمليات",
        science: "العلوم",
        finance: "المالية",
        facilities: "المرافق",
        procurement: "المشتريات",
        "2minAgo": "منذ دقيقتين",
        "15minAgo": "منذ 15 دقيقة",
        "1hourAgo": "منذ ساعة",
        "3hoursAgo": "منذ 3 ساعات",
        "5hoursAgo": "منذ 5 ساعات",
        yesterday: "أمس",
        completed: "مكتمل",
        pending: "معلق",
        inProgress: "قيد التنفيذ",
        totalWorkshops: "إجمالي الورش",
        upcoming: "قادمة",
        systemOverview: "نظرة عامة على النظام",
        signoutConfirm: "هل أنت متأكد من عملية تسجيل الخروج؟",
        cancel: "إلغاء",
        noData: "لا توجد بيانات",
        noDataDesc: "ستظهر البيانات هنا عند اتصال النظام بالخادم",
        quickActions: "إجراءات سريعة",
        systemStatus: "حالة النظام",
        servers: "الخوادم",
        database: "قاعدة البيانات",
        backup: "النسخ الاحتياطي",
        connected: "متصل",
        awaitingSetup: "في انتظار الإعداد",
        notConfigured: "غير مُهيأ",
        noNotifications: "لا توجد إشعارات حالياً",
        weeklyAttendance: "تحليلات الحضور الأسبوعية",
        attendanceComparison: "مقارنة نسب الحضور خلال أيام الأسبوع",
        attendanceLabel: "الحضور",
        operational: "يعمل بكفاءة",
        maintenance: "صيانة",
        setupRequired: "مطلوب إعداد",
        welcomeTitle: "مرحباً بك مجدداً",
        welcomeSubtitle: "إليك نظرة عامة على عمليات المدرسة اليوم",
        inactive: "غير نشط",
        students: "إدارة الطلاب",
        studentsDescription: "إدارة سجلات الطلاب والتسجيل والتقدم الأكاديمي.",
        totalStudents: "إجمالي الطلاب",
        newEnrollments: "تسجيلات جديدة",
        activeStudents: "الطلاب النشطون",
        graduated: "خريجون",
        rollNumber: "رقم الجلوس",
        grade: "المرحلة",
        parentName: "اسم ولي الأمر",
        studentClass: "الفصل",
        recentReports: "التقارير الأخيرة",
        filterReports: "تصفية التقارير",
        scheduleAutoReports: "جدولة تقارير تلقائية",
        scheduleDesc: "قم بإعداد تقارير دورية تصلك مباشرة على بريدك الإلكتروني كل أسبوع.",
        startScheduling: "ابدأ الجدولة الآن",
        saveChanges: "حفظ التغييرات",
        changePassword: "تغيير كلمة المرور",
        receiveEmailUpdates: "تلقي تحديثات النظام عبر البريد",
        browserPushNotif: "إشعارات المتصفح المنبثقة",
        extraSecuritySMS: "تأمين إضافي عبر الهاتف",
        mealsServed: "وجبات قُدمت",
        menuItems: "أصناف القائمة",
        totalItems: "إجمالي الأصناف",
        totalPaid: "إجمالي المدفوع",
        sessionSecure: "سيتم إغلاق جلستك الحالية وتأمين حسابك",
        fullAccess: "صلاحيات كاملة",
        editDetails: "تعديل البيانات",
        securityExcellent: "حالة الأمان: ممتاز",
        verifiedEmailPhone: "تم التحقق من بريدك وهاتفك بنجاح",
        adminDept: "الإدارة العامة",
        cairoEgypt: "القاهرة، مصر",
        adminTitle: "مدير النظام",
        pendingFees: "الرسوم المتأخرة",
        searchStudent: "البحث عن الطلاب...",
        searchInventory: "البحث في المخزون...",
        searchMenu: "البحث في القائمة...",
        searchPayroll: "البحث في المسيرات...",
        searchSuppliers: "البحث في الموردين...",
        searchWorkshops: "البحث في الورش...",
        searchAssets: "البحث في الأصول...",
        allGrades: "كل المراحل",
        allClasses: "كل الفصول",
        allCategories: "كل الفئات",
        exportData: "تصدير البيانات",
        addStudent: "إضافة طالب",
        addItem: "إضافة صنف",
        addMeal: "إضافة وجبة",
        processPayroll: "معالجة الرواتب",
        addSupplier: "إضافة مورد",
        addWorkshop: "إضافة ورشة",
        assignAsset: "تعيين أصل",
        inStock: "متوفر",
        lowStock: "مخزون منخفض",
        totalSuppliers: "إجمالي الموردين",
        pendingOrders: "طلبات معلقة",
        overdue: "متأخر",
        curriculum: "إدارة المنهج",
        curriculumDescription: "إدارة المنهج والمقررات والجداول الدراسية.",
        grades: "الدرجات والتقييم",
        gradesDescription: "تتبع درجات الطلاب والتقييمات والأداء الأكاديمي.",
        library: "إدارة المكتبة",
        libraryDescription: "إدارة كتب المكتبة والاستعارة والموارد الرقمية.",
        transportation: "النقل المدرسي",
        transportationDescription: "إدارة الحافلات والمسارات والنقل المدرسي.",
        parent_portal: "بوابة الأهالي",
        parentPortalDescription: "السماح للأهالي بتتبع تقدم الطالب والتواصل.",
        notificationsSystem: "نظام الإشعارات",
        notificationsSystemDescription: "إرسال رسائل قصيرة وبريد إلكتروني وإشعارات فورية.",
        advanced_reports: "التقارير المتقدمة",
        advancedReportsDescription: "إنشاء تقارير تفصيلية مع تحليلات وتصورات بيانية.",
        events: "الفعاليات والأنشطة",
        eventsDescription: "جدولة وإدارة الفعاليات والمسابقات والأنشطة المدرسية.",
        complaints: "الشكاوى والمقترحات",
        complaintsDescription: "إدارة شكاوى ومقترحات الطلاب والأهالي.",
        fees: "إدارة الرسوم",
        feesDescription: "تتبع رسوم الطلاب والفواتير وسجلات الدفع.",
        archive: "الأرشيف الرقمي",
        archiveDescription: "تخزين وإدارة الوثائق الرقمية والسجلات الطلابية.",
        analytics: "لوحة التحكم الذكية",
        analyticsDescription: "عرض التحليلات المتقدمة ومؤشرات الأداء الرئيسية.",
        courses: "المقررات",
        activities: "الأنشطة",
        September: "سبتمبر",
        send: "إرسال",
        manageLand: "إدارة المنهج",
        gradeTable: "جدول الدرجات",
        academicPerformance: "الأداء الأكاديمي",
        borrowing: "الاستعارة",
        searching: "البحث",
        busStatus: "حالة الحافلة",
        parentConnect: "اتصال الأهالي",
        teacherContact: "اتصال المعلم",
        schoolAdmin: "الإدارة المدرسية",
        sendMessage: "إرسال رسالة",
        scheduleReport: "جدولة التقرير",
        competitionsHeld: "المسابقات المقامة",
        complaintStatus: "حالة الشكوى",
        fileList: "قائمة الملفات",
        dashboardMetrics: "مقاييس لوحة التحكم",
        performanceMetrics: "مقاييس الأداء",
        attendanceRate: "معدل الحضور",
        parentSatisfaction: "رضا الأهالي",
        overallGrowth: "النمو الإجمالي",
        academicTrend: "الاتجاه الأكاديمي",
        studentDistribution: "توزيع الطلاب",
        morning: "صباحاً",
        noon: "ظهراً",
        afternoon: "بعد الظهر",
        evening: "مساءً",
        used: "مستخدم",
        documents: "المستندات",
        certificates: "الشهادات",
        urgent: "عاجل",
        views: "عدد المشاهدات",
        message: "الرسالة",
        primary: "ابتدائي",
        preparatory: "إعدادي",
        secondary: "ثانوي",
        averageRating: "متوسط التقييم",
        Student: "الطالب",
        course: "المقرر",
    },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider = ({ children }: { children: React.ReactNode }) => {
    const [language, setLanguage] = useState<Language>(() => {
        const saved = localStorage.getItem("language");
        return (saved as Language) || "ar"; // Default to Arabic as requested by user's theme
    });

    useEffect(() => {
        localStorage.setItem("language", language);
        document.documentElement.dir = language === "ar" ? "rtl" : "ltr";
        document.documentElement.lang = language;
    }, [language]);

    const t = (key: string) => {
        return (translations[language] as any)[key] || key;
    };

    return (
        <LanguageContext.Provider value={{ language, setLanguage, t }}>
            {children}
        </LanguageContext.Provider>
    );
};

export const useLanguage = () => {
    const context = useContext(LanguageContext);
    if (!context) throw new Error("useLanguage must be used within a LanguageProvider");
    return context;
};
